name: rl_repro_lab
channels:
- defaults
- pytorch
dependencies:
- pip=19.2.3
- matplotlib=3.1.1
- numpy=1.17.2
- python=3.6.*
- scipy=1.3.1
- seaborn=0.9.0
- pytorch=1.2.0
- pandas=0.23.0
- pip:
    - gym==0.14.0